### ISSUE TITLE
Your API key is probably invalid or credits have been exhausted

### ISSUE THREAD

**Issue by HenriqueMachado** [vysecurity/DomLink#11]
Hi! I just have downloaded DomLink, got a free api key from whoxy and put on domLink.cfg.
When I run domLink i got:

ERROR:root:WHOIS lookup failed, your API key is probably invalid or credits have been exhausted

What I'm missing?

Thanks

**Comment by whoot** [comment]
You can´t use the Free API key. You have to buy 'API Calls'.

**Comment by Oxicode** [comment]
+1

**Comment by vysecurity** [comment]
Used to work fine for me :)

**Comment by whoot** [comment]
Having the same issue now!
Debugging showed, that there must be some issue with the request. I changed the python file in order to output the result of the first request and then exit.
```
def parse_whois(base_url, domain):
    emails, companies, domains = {}, {}, {domain: False}
    url = '{}&whois={}'.format(base_url, domain)
    content = get(url).json()
    print content 
    exit()
[...]
```


This is the result:
```
python2.7 domLink.py -D REDACTED -A REDACTED 
DomLink Domain Discovery Tool
Author: Vincent Yiu (@vysecurity)
Contributors: John Bond (@b4ldr)
https://www.github.com/vysec/DomLink
Version: 0.1.1

{u'status': 0, u'status_reason': u'Whois Retrieval Failed'}
```

However, if i execute the command manually with wget, I get the whois information back.


EDIT: **THIS SEEMS TO BE AN WHOXY ERROR!** If you are trying to query domains with two TLDs (e.g. "com.br") Whoxy is not able to produce an output...

**Comment by vysecurity** [comment]
Weird. Still works here.

**Comment by d4sh3r** [comment]
root@cyber:/opt/DomLink# python domLink.py -D domain -o domain.out.txt
DomLink Domain Discovery Tool
Author: Vincent Yiu (@vysecurity)
Contributors: John Bond (@b4ldr)
https://www.github.com/vysec/DomLink
Version: 0.1.1

ERROR:root:WHOIS lookup failed, your API key is probably invalid or credits have been exhausted

### Company Names:


### Domain Names:
domain.com

### Email Addresses:

**Comment by vysecurity** [comment]
Update: seems like you need credits these days :)

>

**Comment by spazbg** [comment]
Hello, I have the same problem with my DomLink...
I have purchased API credits, and when trying the API URL I can get the data, but when I am using domLink.py keeps telling me that I have no credits... 
https://i.imgur.com/BH2HW3g.png

**Comment by juniorhero** [comment]
@spazbg I am too getting same error with purchased credits
