### ISSUE TITLE
Console interface

### ISSUE THREAD

**Issue by saeeddhqan** [vysecurity/DomLink#20]
Hi dear,
you can use Maryam for the user interface. If you use Maryam, your program will a framework like Metasploit.
If you wanted, please ask how to work.
[http://github.com/saeeddhqan/maryam](https://github.com/saeeddhqan/maryam)

**Comment by vysecurity** [comment]
Hey,

What’s that?

**Comment by saeeddhqan** [comment]
https://github.com/saeeddhqan/maryam/wiki
You can convert your code into a module, then enter the program and use a much better interface.
