### ISSUE TITLE
DomLink error while having purchased credits 

### ISSUE THREAD

**Issue by spazbg** [vysecurity/DomLink#24]
Hello, I have the same problem with my DomLink...
I have purchased API credits, and when trying the API URL I can get the data, but when I am using domLink.py keeps telling me that I have no credits... 
https://i.imgur.com/BH2HW3g.png

_Originally posted by @spazbg in https://github.com/vysecurity/DomLink/issues/11#issuecomment-671822342_

**Comment by hoacks** [comment]
Did you manage to fix the issue, I'm having the same errror.

**Comment by spazbg** [comment]
Nope...

**Comment by hoacks** [comment]
check out https://github.com/MilindPurswani/whoxyrm , thats working.

**Comment by pdelteil** [comment]
Same problem here.

**Comment by supr4s** [comment]
Same here ! 
```
<class 'type'>
ERROR:root:WHOIS lookup failed, your API key is probably invalid or credits have been exhausted
Traceback (most recent call last):
  File "domLink.py", line 221, in <module>
    main()
  File "domLink.py", line 160, in main
    results['companies'].values() +
TypeError: unsupported operand type(s) for +: 'dict_values' and 'dict_values'

```

**Comment by supr4s** [comment]
In the meantime you can use : https://github.com/gwen001/pentest-tools/blob/master/domain-finder.py

$ ./domain-finder.py -k API_KEY -d mydomain.com

**Comment by hoacks** [comment]
> In the meantime you can use : https://github.com/gwen001/pentest-tools/blob/master/domain-finder.py
> 
> $ ./domain-finder.py -k API_KEY -d mydomain.com
Did you test it, not working for me either.

**Comment by supr4s** [comment]
> > In the meantime you can use : https://github.com/gwen001/pentest-tools/blob/master/domain-finder.py
> > $ ./domain-finder.py -k API_KEY -d mydomain.com
> > Did you test it, not working for me either.

Work like a charm for me !

**Comment by vysecurity** [comment]
I’ll fix it at some point. Didn’t realise so many people were using it :)
