### ISSUE TITLE
api key problem

### ISSUE THREAD

**Issue by shannu3** [vysecurity/DomLink#26]
I have just created an account in whoxy.com and added API key in domLink.cfg file but i was getting this error that API KEY is invalid,so i tried creating another API key , i got the same error again.

<class 'type'>
ERROR:root:WHOIS lookup failed, your API key is probably invalid or credits have been exhausted
Traceback (most recent call last):
  File "domLink.py", line 221, in <module>
    main()
  File "domLink.py", line 159, in main
    while any(results['domains'].values() +
TypeError: unsupported operand type(s) for +: 'dict_values' and 'dict_values'

**Comment by mylesholloway1** [comment]
any luck solving this issue? having the same problem

**Comment by midou979** [comment]
The script must be executed on python2
