### ISSUE TITLE
hidden emails

### ISSUE THREAD

**Issue by gwen001** [vysecurity/DomLink#4]
Hi,

Sometimes emails are hidden: `********@*****.***`
This crash the program in the next step:
```
Traceback (most recent call last):
  File "domLink.py", line 176, in <module>
    expand()
  File "domLink.py", line 150, in expand
    pages = content["total_pages"]
KeyError: 'total_pages'
```

I think you should add a test to check the presence of `total_pages` but for now I added a very small function to test the email (a regexp would be much better but Python is not my cup of tea):

```
def append_email(email):
        if email.find('*') == -1:
	        company_emails.append(email)
```

Then replace:
```
company_emails.append(...)
```
By:
```
append_email(...)
```

Best regards,

Gwen

**Comment by vysecurity** [comment]
I'll add a try except to it just to catch it. You're supposed to type "n" when it prompts for such an email. But hmm... yeah.

**Comment by vysecurity** [comment]
Thanks! I'll take a look when I have a moment.
